### ISSUE TITLE
I can only type English in Archlinux Gnome3

### ISSUE THREAD

**Issue by osfans** [cogniti/dasom#10]
I install dasom from aur.
I can only type English in Archlinux Gnome3.
How to switch to Hangul or Hanja?

Thanks!

**Comment by cogniti** [comment]
Did you update gtk im cache?
What is your keyboard model name?

**Comment by osfans** [comment]
I use US 101 PC keyboard which is common in China.
I select "Right Ctrl as Hangul, Right Alt as Hanja" from gnome-tweak-tool, and it works!

Thanks!

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#10
