### ISSUE TITLE
Qt Creator 에서 한글입력이 안됩니다.

### ISSUE THREAD

**Issue by norux** [cogniti/dasom#11]
우선 증상은 Qt Creator내에 커서가 위치하면 다솜 입력기 트레이에 en, ko 둘 다 나오지 않고 있습니다.
그리고 한글 입력은 되지않으며, 영문 입력만 가능합니다.

우분투 14.04 64bit 버전입니다.

Qt Creator 버전: 3.4.1 (opensource)
Based on Qt 5.4.2 (GCC 4.6.1, 32bit) 입니다.
revision: 29d81424a2

**Comment by cogniti** [comment]
Qt 버전에 따른 호환성 문제 같습니다. 확인하여 다솜 입력기의 호환성을 향상시킬 예정입니다. 감사합니다.

**Comment by cogniti** [comment]
우분투 14.04 에 있는 Qt5 버전이 5.2.1 입니다. 그런데 norux님은  Qt 5.4.2 사용 중이므로,
현재 사용 중인 다솜 입력기가 https://github.com/cogniti/dasom/releases 에서 deb 파일을 다운받아 설치하신 것이라면... 소스코드 다운받아서 다시 컴파일하여 설치해 보시기 바랍니다.
그리고 나서 입력이 되는지 안 되는지 알려주세요.

**Comment by cogniti** [comment]
컴파일하여 설치하시는 것이 곤란하시면, 
Qt5의 어떤 버전에서 Qt5 모듈이 로딩되지 않는지 알아야 하므로
Qt Creator 버전: 3.4.1 (opensource)
Based on Qt 5.4.2 (GCC 4.6.1, 32bit)
이걸 설치하는 방법을 알려주세요.

**Comment by norux** [comment]
qt-creator는 Qt 공식홈페이지에서 현재 배포하는 버전에 맞춰서 빌드되는것 같습니다.
http://download.qt.io/official_releases/qtcreator/3.5/3.5.1/
위 버전이 현재 공식적으로 Qt에서 배포하는 최신 버전입니다. 위 버전에서도 다솜입력기가 안되는걸 확인했습니다.

다솜입력기 직접 컴파일해서 다시 해보고 댓글달겠습니다.

**Comment by cogniti** [comment]
5.5.1 의 경우 다솜 입력기 버그를 제가 확인했습니다.
아래처럼 바꾸면 아치리눅스에서 작동은 합니다.
우분투 15.10 에 Qt 5.4.2 가 들어가 있던데... 패치 적용 전, 적용 후 모두 그게 작동을 하지 않아서 확인 중에 있습니다.
```diff
diff --git a/modules/clients/qt5/Makefile.am b/modules/clients/qt5/Makefile.am
index d2b9474..6b1da05 100644
--- a/modules/clients/qt5/Makefile.am
+++ b/modules/clients/qt5/Makefile.am
@@ -3,6 +3,7 @@ QT5_GUI_VERSION      = `pkg-config --modversion          Qt5Gui`
 QT5_GUI_INCLUDE_DIR  = `pkg-config --variable=includedir Qt5Gui`
 QT5_GUI_INCLUDE_PATH = $(QT5_GUI_INCLUDE_DIR)/QtGui/$(QT5_GUI_VERSION)/QtGui
 
+# archlinux qt5 module dir /usr/lib/qt/...
 qt5_im_moduledir = $(QT5_LIB_DIR)/qt5/plugins/platforminputcontexts
 qt5_im_module_LTLIBRARIES = libqt5im-dasom.la
 
@@ -27,7 +28,7 @@ libqt5im_dasom_la_LDFLAGS = -avoid-version -module \
 libqt5im_dasom_la_LIBADD  = $(top_builddir)/libdasom/libdasom.la
 
 im-dasom-qt5.moc: im-dasom-qt5.cpp
-       $(AM_V_GEN) $(QT5_MOC) im-dasom-qt5.cpp -o im-dasom-qt5.moc
+       $(QT5_MOC) -I $(QT5_GUI_INCLUDE_PATH) im-dasom-qt5.cpp -o im-dasom-qt5.moc
 
 install-data-hook:
        chmod -x $(DESTDIR)$(qt5_im_moduledir)/libqt5im-dasom.so
diff --git a/modules/clients/qt5/im-dasom-qt5.cpp b/modules/clients/qt5/im-dasom-qt5.cpp
index 6363148..558814d 100644
--- a/modules/clients/qt5/im-dasom-qt5.cpp
+++ b/modules/clients/qt5/im-dasom-qt5.cpp
@@ -348,7 +348,7 @@ class DasomInputContextPlugin : public QPlatformInputContextPlugin
 {
   Q_OBJECT
   Q_PLUGIN_METADATA(IID
-    "org.qt-project.Qt.QPlatformInputContextFactoryInterface"
+    QPlatformInputContextFactoryInterface_iid
     FILE "./dasom.json")
 
 public:
```

**Comment by norux** [comment]
![2015-10-17 10 44 41](https://cloud.githubusercontent.com/assets/4457861/10556377/3b9ed538-74bc-11e5-800e-cc518545c4a7.png)

수정했지만 여전합니다.
버전 정보는 캡쳐로 보시는 것과 같고, 다솜입력기의 경우 소스코드를 clone받아서 빌드한 버전입니다.
빌드할 때, Qt5.5.1 라이브러리를 사용하도록 수정하여 빌드했습니다.

그리고 혹시 참조가 될까해서 말씀드리는 건데, 기존에 nabi, uim같은 입력기도 Qt Creator에서는 제대로 동작하지 않았습니다. ibus만 끝글자 띄어쓰기 버그와 함께 한글 입력이 되서 사용해왔습니다.

**Comment by cogniti** [comment]
우분투 15.10 에 Qt 5.4.2 가 기본으로 들어 있는데... 다솜에 위 패치 적용하면 적용이 됩니다.
다만, ibus 를 제거해야 `QT_IM_MODULE="dasom"` 이렇게 자동으로 설정이 됩니다.
(그 점은 im-config 으로 fcitx를 선택하여도 마찬가지입니다.)
아치리눅스는 q5 디렉토리가 아닌 qt 이므로 그 점을 고려하여 위 패치를 약간 수정하여 적용될 예정입니다.
감사합니다.

**Comment by cogniti** [comment]
아... 참고로 다솜 버그가  Qt 5.4.2 버전에 영향을 주지 않습니다. 영향받는 버전은 Qt 5.5.1 입니다.
다솜 및 fcitx 에서 Qt 5.4.2 어플이 작동하지 않으면 ibus 를 삭제해보시길 바랍니다.
감사합니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#11
