### ISSUE TITLE
두벌식: ㄱㄱ,ㅅㅅ,ㅂㅂ 입력안됨

### ISSUE THREAD

**Issue by piriripipipi** [cogniti/dasom#13]
ㄱㄱ 두번 누르면 ㄲ 되버립니다. 제가 ㅎㄷㄷ 쓰기를 참 좋아하는데요. ㅎㄸ이 되어버립니다.

버그가 아니라면 선택 할 수 있게 옵션추가 부탁드립니다.

**Comment by cogniti** [comment]
저도 원하는 사항입니다.
다솜 입력기의 한글 엔진은 libhangul 을 사용하고 있습니다. 위의 현상은 버그는 아닙니다. 관련 이슈가 libhangul 프로젝트에 계류 중에 있습니다. https://github.com/choehwanjin/libhangul/pull/3
4년 정도 된 이슈라서 기대는 안 하시는 것이 좋겠습니다.
참고로, 제가 현재 한글 오토마타를 만들 계획은 없습니다.
여러 이슈 및 개발 계획 때문에 이 이슈가 처리되려면  수년이 걸릴지도 모르겠습니다.

**Comment by iyagicom** [comment]
민트 17에서 리브레, 파이어폭스에서 해보고 있는데 전 그렇게 안되는데요?
ㄱㄱ , ㅎㄷㄷ

그려고 보니 다솜입력기 캡스락 버그?(또는 의도?)가 잡혔네요
그전껀 캡스락키를 눌려져있고 ㄱ를 쓰면 ㄲ이 써졌거든요

**Comment by cogniti** [comment]
원래는 ㄱ+ㄱ = ㄱㄱ 이 되어야 맞습니다. 쉬프트가 괜히 있는게 아니므로... 버그로 인식하여 해결하도록 하겠습니다. 두벌식의 경우, libhangul 에 키값을 보내기 전에 preedit 를 체크하는 방법을 사용하면 간단하게 해결이 될 것 같습니다. 제가 세벌식을 모르기 때문에 세벌식 자판도 위의 방법을 쓰면 해결이 되는지는 좀더 생각해봐야 합니다.

**Comment by cogniti** [comment]
제가 세벌식을 잘 모르는데다가 사용을 하지 않기 때문에 섯불리 이 기능을 세벌식에 추가하면 테스트도 안 될 뿐더러 버그만 양산하게 되므로, 우선은 두벌식에만 적용할 계획이며 늦어도 11월까지는 해결될 예정입니다. 그리고 세벌식의 경우 필요하신 분이 계시다면 따로 이슈를 올려주시기 바랍니다.
감사합니다.

**Comment by cogniti** [comment]
`"double-consonant-rule"` 옵션을 제공합니다. 기본값은 `false`  입니다.
기본 동작(`false`)으로 초성 `ㄱ ㄷ ㅂ ㅅ ㅈ` 자음에 대하여 동일 키를 두번 눌러도 겹자음으로 출력하지 않도록 합니다.

예전처럼 동일키를 두번 눌렀을 때 겹자음으로 조합하려면 `"double-consonant-rule"`  옵션에 체크하여 `true`를 하시면 되겠습니다.

옵션은 실시간으로 적용되므로 로그아웃/로그인할 필요가 없습니다.
감사합니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#13
