### ISSUE TITLE
Caps Lock이 눌려져 있으면 한/영 바꿈이 안되네요.

### ISSUE THREAD

**Issue by iyagicom** [cogniti/dasom#15]
왜 안바끼는지 햇는데 오늘 찾았어요~

**Comment by cogniti** [comment]
MS 윈도 XP에서는 Caps Lock 눌러져 있을 때에도 한/영 전환이 되는군요.
Caps Lock 상태일 때도 한/영 전환이 되도록 수정하겠습니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#15
