### ISSUE TITLE
Android Studio 1.4에서 Caps Lock 키가 안먹혀요.

### ISSUE THREAD

**Issue by iyagicom** [cogniti/dasom#16]
Caps Lock 키가 눌려져 있을때 영타를 하면 대문자가 써저야 되는데 소문자로 써져요.
올래 Andoid Studio에서 그런지는 모르겠는데 그러진 않을것 같고요.
 리브레, 파폭에서는 잘되요

**Comment by cogniti** [comment]
다솜 입력기의 이벤트를 변환부의 문제일 수도 있습니다.
조만간 확인해보겠습니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#16
