### ISSUE TITLE
Firefox 사용시, GitHub 코드 에디터 화면에서 한글 입력시 Firefox가 강제종료됨.

### ISSUE THREAD

**Issue by sukso96100** [cogniti/dasom#18]
Firefox 사용시, GitHub 에서 Gist 수정이나 코드 수정 화면에서, 한글 약 3~4 글자 입력하면, 파이어폭스가 작동을 멈춥니다. 그리고 창이 응답하지 않는다고 다이얼로그가 뜨는군요. 참고로 크롬에서는 이러한 증상이 없습니다.

**Comment by cogniti** [comment]
확인해보겠습니다.

**Comment by cogniti** [comment]
파일이 약 1000줄 정도 되는데...
https://github.com/cogniti/dasom/blob/master/libdasom/dasom-server.c
"Edit this file" 클릭해서 편집 모드로 들어가서 마우스 한번 살짝 클릭을 10초 간격으로 여기 저기 클릭하면서 1분 정도 아무키나 막 누르니까... iceweasel(데비안에서 파이어폭스 이름) 이 죽었습니다.
그래서 통신 구조가 아닌 `imhangul` 로 테스트해보니 마찬가지 현상이 발생했습니다.
```
hodong@debian:~$ iceweasel 

(process:25762): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
Vector smash protection is enabled.
[NPAPI 25821] ###!!! ABORT: Aborting on channel error.: file /tmp/buildd/iceweasel-38.3.0esr/ipc/glue/MessageChannel.cpp, line 1584
[NPAPI 25821] ###!!! ABORT: Aborting on channel error.: file /tmp/buildd/iceweasel-38.3.0esr/ipc/glue/MessageChannel.cpp, line 1584
Segmentation fault
hodong@debian:~$ a,.u
```
로그가 이렇게 나오는군요.
그런데 두 경우(dasom, imhangul) 파폭(iceweasel 38.3.0)이 멈추지는 않고 그냥 죽었습니다.
특이점은... 다솜 입력기의 경우 의도하지 않았는데 한/영 전환이 바뀌기도 하였습니다.
imhangul 은 한/영 전환이 바뀐 적이 없었습니다.

ibus, imhangul 로도 테스트해보시고 상태가 어떠한지 알려주시면 고맙겠습니다.

**Comment by sukso96100** [comment]
ibus-hangul 를 그놈 키보드 설정에서 입력소스로 추가 후 사용시에는 아무 문제 없이 잘 입력됩니다.

**Comment by cogniti** [comment]
파이어폭스 41.0.2 에서 재현할 수 있습니다. 다솜 입력기 버그입니다.
이러한 버그는 귀중한 버그인데... 감사합니다.

**Comment by cogniti** [comment]
이 버그는 당장 살펴봐야 하는 중요도 높은 버그인데...
debian/copyright 파일에 IMdkit 라이선스를 실수로 빠뜨려서 그 작업을 먼저 한 후에 처리하도록 하겠습니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#18
