### ISSUE TITLE
우분투 15.10 qtbase-abi-5-4-* 패키지 오류

### ISSUE THREAD

**Issue by parkmino** [cogniti/dasom#19]
방금 우분투 판올림을 했는데, 위 패키지가 없다며 실행이 되지 않네요.
수정 부탁 드립니다.

**Comment by cogniti** [comment]
우분투 15.10 이 정식 버전으로 나왔군요.
재컴파일해야 될 겁니다.
버추얼박스에 깔고 deb 만들려면 시간 좀 걸립니다.
오늘은 어렵고 내일쯤 파일 올라갈 겁니다.
알려드리겠습니다.

**Comment by parkmino** [comment]
네, 그냥 컴파일만 새로하면 되는 거 였군요.
방금 다솜 컴파일해서 쓰고 있습니다.
시간 나실 때 설치 파일 올려주시면 감사하겠습니다.

**Comment by cogniti** [comment]
dasom 1.0 소스로 우분투 15.10에서 컴파일해보니 에러가 나는군요. 그 에러는 이후 커밋에서 해결되었습니다. 나중에 릴리즈 작업할 때 우분투 15.10 패키지 만들어야겠습니다.

**Comment by iyagicom** [comment]
다솜 1.0.1
우분투 15.04에서 qtbase-abi-5-4-2 의존성 에러 나오네요

**Comment by cogniti** [comment]
재컴파일해야 될 거 같네요

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#1

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#19
