### ISSUE TITLE
GNOME 3.18 Support for Dasom Agent GNEOM Extension

### ISSUE THREAD

**Issue by sukso96100** [cogniti/dasom#2]
dasom agent extension 이 GNOME 3.18 을 지원하지 않는군요. 지원 추가해 주시면 감사하겠습니다.

**Comment by cogniti** [comment]
아래 파일을 보면...
dasom/agents/gnome-shell-extension/metadata.json.in
"shell-version": [ "3.14", "3.16" ], 이 부분을
"shell-version": [ "3.14", "3.16", "3.18" ],
gnome-shell 버전에 따라서 api 가 달라지는 경우가 있어서 장담을 못하겠습니다.
변경해보시고 되는지 안되는지 말씀 좀 해주세요.
"3.18" 문구를 추가하여 작동이 되면 pull request 부탁 드립니다.

**Comment by sukso96100** [comment]
넵. 한번 해보고 되면 pull request넣고 안되면예기해 드리겠습니다.

**Comment by cogniti** [comment]
gnome-shell 이 버전이 올라가면서 api 가 변경되기도 하며 하위 호환성도 제공해야 하고 디버깅이 어려워 gnome shell extension 개발에 곤란한 점이 있습니다. 그래서 좀 알아보니...

appindicator 를 그놈 쉘 패널에 표시해주는 확장이 있습니다.
https://github.com/rgcjonas/gnome-shell-extension-appindicator
https://extensions.gnome.org/extension/615/appindicator-support/
이걸 웹 브라우저로 설치해보니... 어떤 원리인지는 모르겠지만, 윈도우키 + M 눌렀을 때 하단에 나오던 dasom-indicator 가 사라지고 dasom-indicator 가 패널 상단 우측에 표시가 됩니다.

gnome-shell-extension-appindicator 을 사용하면 개발 시간을 절약하면서 중복 코드가 줄어들며 표시기 개발을 단일화할 수 있고, dasom-indicator 는 별도의 프로세스로 작동하는 프로그램이므로 GtkWindow 를 그리는 코드를 삽입하고 그것을 옵션으로 제공하면 sawfish 같은 창관리자를 사용하는 환경에도 적용이 가능할 것 같습니다.

그래서 표시기 어플로써 appindicator 을 이용한 dasom-indicator 만 개발하는 것을 고려 중에 있습니다.
gnome-shell 환경에서는 gnome-shell-extension-appindicator 를 설치하면 dasom-indicator 를 패널에 표시할 수 있습니다.

**Comment by cogniti** [comment]
아치 리눅스 GNOME shell 3.18.0 에서 작동됩니다. 감사합니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#2
