### ISSUE TITLE
README에 우리말로도 써 주시면 어떨까요?

### ISSUE THREAD

**Issue by sebuls** [cogniti/dasom#20]
dasom 을 다른 나라 사람들보다 우리나라 사람들이 많이 쓸텐데 한국어 설명이 있으면 더욱 좋겠습니다.

**Comment by cogniti** [comment]
세벌님은 예전에도
https://forum.ubuntu-kr.org/viewtopic.php?f=6&t=27632#p123461
README 파일 한국어로 써달라고 그러신 적이 있죠.
몰라서 질문하신 것 같지는 않는데...
이러시면 곤란합니다.
README 를 한국어로 쓰면 https://github.com/cogniti/dasom 에 한국어로 나오게 되므로 중국인,일본인, 영어권 사람들이 이해할 수 없습니다.
그리고 uim 프로젝트... 그거 일본어로 되어 있지 않습니다. 그 덕분에 한국사람도 이해할 수 있는거죠.
dasom 을 일부러 한국어로 작성하여 한국 내에만 고착시킬 필요는 없는거죠.
그리고 dasom 은 다국어 입력기 프레임워크입니다.
앞으로 뻔히 다 아시면서 일부러 이렇게 시간뺏는 일 제발 하지 마세요.
그리고 제가 지금 포도막염 1기~2기 정도 되는데, 거의 다 나았다가 주말에 당신 때문에 스트레스 받아서 말짱 도로묵되었습니다.
제발 부탁인데 이러지 마세요.

**Comment by cogniti** [comment]
README.ko 이런 파일 하나 만들어서 한국어로 작성하면,
README 파일 바꿀 때마다 README.ko 도 같이 바꿔야하므로 작업량이 늘어납니다.
그래서 못 합니다. 이 프로젝트는 돈받고 하는 프로젝트도 아니고,
제가 이거 하면서 어디서 돈나오는 거 아니고, 저는 생업이 따로 있는 사람입니다.

**Comment by cogniti** [comment]
이 이슈는 동일인의 악의성 이슈로 판단됩니다.
https://github.com/cogniti/dasom/issues/17
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28305
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28318
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28316
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28262&start=40#p125571
https://ask.ubuntu-kr.org/?qa=304/%EB%8B%A4%EC%86%9C%EC%9E%85%EB%A0%A5%EA%B8%B0%EC%97%90%EC%84%9C-shift-space%EB%A1%9C-%ED%95%9C%EC%98%81%EC%A0%84%ED%99%98%EC%9D%B4-%EC%95%88%EB%90%98%EB%82%98%EC%9A%94

**Comment by cogniti** [comment]
본의 아니게 이렇게 글을 쓰게 되어 유감입니다.

> http://cafe.daum.net/3bulsik/6CY8/343
> 리눅스에서 한글입력기 다솜 소식|지식/정보 나눔터
> 세벌
> | | 조회 47 |추천 0 | 2015.10.27. 12:37 http://cafe.daum.net/3bulsik/6CY8/343 
> https://github.com/cogniti/dasom
> 리눅스에는 입력기가 여러가지 있는데 얼마전에 새로운 입력기가 나왔습니다.
> 위 사이트에는 거의 영어인데 개발자는 우리나라 사람입니다.
> 참고하셔요.

세벌님이 왜 자꾸 절 음해하려 하는지 이해가 되지 않습니다.
이미 우분투 포럼에서도 몇 차례 이런 일이 있었습니다.

다솜 입력기는 정확히는 ibus, fcitx, uim 같은 다국어 입력기 프레임워크입니다.
그냥 한글 입력기가 아닙니다.
다솜 프로젝트는 다국어 입력기 프로젝트이며,
https://github.com/cogniti/dasom
프로젝트 사이트는 개발자 사이트이며, README 파일은 외국인 개발자를 위해 영어로 작성했습니다.
fcitx, ibus, uim 프로젝트는 주 개발자가 중국인, 일본인인데도 왜 영어를 사용하고 있을까요.
http://github.com/ibus/ibus
https://github.com/fcitx/fcitx
https://github.com/uim/uim
리눅스의 주 개발자는 영미권 개발자들입니다. 이들에게 중국어, 일본어, 한국어(CJK) 입력 방식을 이해시켜야 한국어 지원이 좋아지게 됩니다.

저는 이미 과거 libhwp (hwp 라이브러리) 개발, klavaro 타자 연습기 한국어 지원한 바 있고
지금은 다솜 입력기에 한국어 엔진을 탑재했고 이제는 중국어 엔진을 준비하고 있습니다.
사실 이해가 되지 않는 것이 있는데, 한글/한국어 관련하여 뭔가 해보려고 하면 피곤한 일들이 많이 발생하더군요.
저를 음해하는 행위를 중단하지 않을 경우,
다솜 입력기에서 한국어 엔진을 분리하고 더 이상 유지보수를 하지 않을 수도 있습니다.

감사합니다.


https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28305
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28316
https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28318
https://forum.ubuntu-kr.org/viewtopic.php?f=6&t=27632#p123461

**Comment by cogniti** [comment]
다솜 입력기에서 한글 엔진을 제거할 것이니 음해하는 행위를 중단하시기 바랍니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#20
