### ISSUE TITLE
정보 눌렸을때 버전있으면 좋겠어요

### ISSUE THREAD

**Issue by iyagicom** [cogniti/dasom#21]
정보에 버전이 안써져 있으니 몇인지 모르겠어요.
1.0.1로 업데이트 했을때, 이미 깔려져 있다고 해서 1.0버전이 깔려져 있어서 그런가 하고 지우고 다시 깔았어요
더 바란다면,
한영키를 키나 키조합으로 바꿀 수 있는 옵션이 있으면 더 좋겠고요.

그리고,
Caps Lock 키에 대해 고쳐주셔서 감사합니다~
아주 잘 되네요~

그리고,
Caps Lock키가 눌려져 있을때 숫자키의 특수문자가 써지니 완전 편한것 같아요.
이기능은 꼭 가지고 갔으면해요.

**Comment by cogniti** [comment]
1. 정보(About)에 버전 추가하겠습니다. 우선은 `dasom-daemon --version` 이렇게 하시면 버전을 보실 수 있습니다.
2. 한영키를 키나 키조합으로 바꿀 수 있는 옵션은 지금 작업하면 작업이 중복되기 때문에 중국어 엔진 설계할 때 만들 예정입니다.
3. Caps Lock키가 눌려져 있을때 숫자키를 누르면 숫자만 나와야 되는데,,, 특수문자가 써진다는 건가요? 아니면 Caps Lock키가 눌려져 있을때 숫자키를 누르면 특수문자 나오게 해달라는 말씀인가요?

**Comment by cogniti** [comment]
3번의 경우, Caps Lock키가 눌려져 있을때 숫자키를 누르면 숫자만 나와야 합니다. MS윈도XP 켜서 확인해봤는데 Caps Lock 눌러져 있을 때 숫자키 누르면 숫자만 나옵니다.
아마 Caps Lock키가 눌려져 있을때 숫자키의 특수문자를 출력해달라는 말씀같은데... 그건 일반적인 방법이 아니기 때문에 받아드릴 수가 없습니다.
그리고 다음부터 이슈 쓰실 때, 제목 당 1개씩 써주세요. 한 제목에 3개를 넣으셨는데 그렇게 하시면 관리가 어렵습니다.
1,2번의 경우 중국어 엔진 설계 들어가면 그 때쯤에 추가될 겁니다. 감사합니다.

**Comment by cogniti** [comment]
2번에 대한 관련 이슈입니다. #17

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#21
