### ISSUE TITLE
한자 목록 버그

### ISSUE THREAD

**Issue by shuggiejang** [cogniti/dasom#22]
https://www.youtube.com/watch?v=GHIEKoNDScs

버그 내용: 한자를 연이어 입력할 때, 방향키를 조작하지 않으면 한자 목록이 갱신되지 않는 버그
OS: linuxmint-17.1-cinnamon-64bit
설치: dasom_1.0.1-ubuntu-14.04_amd64.deb

**Comment by cogniti** [comment]
이 문제는 제가 알고 있는 모든 버그/이슈를 해결한 후에 중국어 엔진 설계하면서 해결하도록 하겠습니다.

**Comment by cogniti** [comment]
부득이한 사정으로 다솜 입력기에서 한국어 엔진을 제거하기로 하였습니다. 따라서 이 이슈를 닫겠습니다.
죄송합니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#22
