### ISSUE TITLE
Delete키를 눌렀을 때, 오른쪽 글자가 지워졌으면 합니다.

### ISSUE THREAD

**Issue by lockpick** [cogniti/dasom#23]
일반적으로 delete를 눌렀을 때, 오른쪽 글자가 지워지는 것을 기대합니다.
하지만, 한글입력 도중 delete키를 누르면, 바로 전에 작성한 글자의 자모가 지워집니다.

예를 들면 아래와 같습니다:
'한인'을 입력한뒤;
커서를 '한'와 '인'사이로 이동하고;
'국'을 입력한 후 delete키를 누르면 아래와 같이 됩니다.

한구인

보통, '한국' 과 같이 오른쪽 글자가 지워지기를 원할 듯 합니다.

**Comment by cogniti** [comment]
Delete 키 누르면 자소가 삭제되는 게 정상인 줄 알았습니다. MS 입력기도 그렇게 작동하는 줄 착각하고 있었습니다. MS 입력기처럼 작동하도록 하겠습니다.

**Comment by lockpick** [comment]
최신 커밋을 적용하여, 삭제하고 다시 빌드하고 설치해보았습니다.
설치는 AUR로 하였습니다.
어차피 git의 내용을 가져와서 빌드하는 것이니, 차이는 없을 듯 합니다.
재부팅까지 해보았는데도, 해당 문제가 여전히 남아있습니다.
빌드한 소스파일을 보아도, 커밋 2b5ce45이 잘 적용된 상태 였습니다.

**Comment by cogniti** [comment]
어플 버그입니다. 파이어폭스와 크롬으로 각각 해보시면 알 수 있습니다. Delete 키 눌렀을 때 입력기는 그 키를 소비하지 않으므로 FALSE를 리턴하며, 이걸 응용 어플에서 처리해야 하는데 그 처리를 하지 않아서 발생하는 현상입니다.

**Comment by lockpick** [comment]
AUR을 통해서 설치했을 때는 파이어폭스 뿐만 아니고 다른 프로그램에서도 안됬었습니다.
git으로 설치하니까 제대로 적용되네요. 파이어폭스든 크로미움이든 정상작동 했습니다.

sukso96100 님이 해결하실 부분인 듯 하네요...

**Comment by sukso96100** [comment]
안녕하세요, @lockpick 님. 전 방금 ``yaourt -S dasom-git`` 명령 실행하여 업데이트 했는데. 아래 예시처럼 잘 작동합니다.
참고로 저는 업데이트 후 다시 부팅 하였습니다.

 - ``한인`` 입력.
 - ``한`` 과 ``인``사이로 커서 이동.
 - ``국`` 입력.
 - Delete 키 누름.
 - ``인`` 지워짐. ``한국`` 만 남음.

아래는 현제 제가 사용중인 ``dasom-git`` 패키지 버전 정보입니다.
```bash
youngbin@youngbin-desktop ~> pacman -Q dasom-git
dasom-git 265.2300f58-1
```

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#23
