### ISSUE TITLE
More wine problem

### ISSUE THREAD

**Issue by yelled1** [cogniti/dasom#24]
나비의 크롬 때문에 고민 했는데 여러 문제를 해결한 새로운 리눅스용 한글 입력기를 출시하신 노고에 감사드립니다. 크롬에 문제 없이 잘 돌아가네요! 그런데 혹시 와인에서 카카오톡을 사용을 해 보셨나요?
크롬에서 생기던 같은 문제가 카카오톡에서 생깁니다. 물론 꼭 다솜 문제라고 생각하지는 않으나 혹시 가능하시면 대응을 하셨으면 감사하겠습니다. 카카오에는 이메일을 보냈으나 답을 기대하지 않고 있습니다.

추가로 같은 현상이 한컴 오피스 한word 2010과 "집이이 투투룸이이어서서"
MS Office 2010 Word "뭔가가 이상한한 상황이이벌어지고고있느느"
에서도 나오고 있습니다. 와인과 호환이 잘 안되네요.

감사합니다,

다솜 1.01 dasom_1.0.1-ubuntu-14.04_amd64.deb 을
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by cogniti** [comment]
안그래도 WINE 쪽이 궁금했었는데 감사합니다.
조만간 확인해보겠습니다.

**Comment by yelled1** [comment]
아참 제 wine과 winetricks version은
$ wine --version
wine-1.7.50
$ winetricks --version
20141130 - sha1sum: 7f03acb40d7fe3b6f3a1477ff936b3b17886e634
입니다. 둘다 모두 최신 version 입니다.
빠른 답변 감사드립니다.
추가로 Kakao Talk은 나비에서 같은 문제가 일어납니다.

**Comment by cogniti** [comment]
10월 26일 커밋  https://github.com/cogniti/dasom/commit/2300f58827d2f7be874965083ac2bc97d5ca737d 으로 개선된 것 같습니다.
https://github.com/cogniti/testing/releases 에 2015.10.26 까지 적용된 deb 파일 올려놓았습니다.
chromium 을 XIM 으로 접속한 것과 약간 다른 것 같은데, 사용해보시고 스페이스 문제, 조합 중 끝글자 상태 등에 대하여 의견 주시기 바랍니다.

관련 이슈입니다.
https://github.com/cogniti/dasom/issues/8#issuecomment-151140355

**Comment by cogniti** [comment]
XIM 부분은 응용 프로그램(libreoffice, wine, chromium 등)이 구현이 제각각이라 현재 dasom-server.c dasom-connection.c 에 들어 있는 xim 처리 부분을 어떻게 변경해야 하는지, 어느 프로그램에 맞추어야 하는지 사실 잘 모르겠습니다.

**Comment by yelled1** [comment]
새로 만들어 build 해주신 deb를 사용해 보니 (빠른 대처에 감사드립니다)
wine 한컴 "뭔가 이제   될거라   생각되었지만 아직  문제가가 존재함 "
wine Kakao "여러가지지문재가 아직도 존재함 " 

space bar을 누를 때 가끔 문제가 아직 존재 합니다.

그리고 한가지 더 이상한 점은 im-config 사용 후에도 (이게 문제해결에 도움이 될지 모르겠습니다)
$ cat .xinputrc
# im-config(8) generated on Tue, 27 Oct 2015 17:19:38 +0900
run_im dasom
# im-config signiture: e6e0f501da4986154bdeb5e90f783f37  -
은 맞는것 같은데 

$ls -l .xinput.d
total 0
lrwxrwxrwx 1 hyoon hyoon 28 Apr 20  2014 en_US -> /etc/X11/xinit/xinput.d/nabi
아직 나비로 연결되어 있습니다. im-config가 제데로 작동하지 않는 것 같습니다.

그리고 $ls -l /etc/X11/xinit/xinput.d/ 해보면
total 4
lrwxrwxrwx 1 root root 30 Oct 27 20:13 ko_KR -> /etc/alternatives/xinput-ko_KR
-rw-r--r-- 1 root root 63 Feb  2  2013 nabi

**Comment by cogniti** [comment]
export | grep dasom
해보고
export XMODIFIERS="@im=dasom"
이게 나오는지 확인하세요
2015. 10. 28. 07:29에 "yelled1" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
한컴 오피스, MS 오피스가 없어서 오피스 테스트는 못하고, 카카오톡 실행하여 계정에 한글로 쳐보니 나비와 증세가 비슷하더군요. 카카오톡을 사용하지 않는 관계로, 로그인 및 카카오톡 대화는 해보지 않았습니다. 다솜이 나비와 증세가 비슷하면 다솜의 XIM 부분은 별로 이상은 없는 것 같습니다.
카카오톡 계정에 한글을 입력하다가 iceweasel 을 클릭하니 카카오톡에 있던 끝글자가 iceweasel 에 찍히네요. 다솜 한글 엔진이 싱글톤 방식이라 원리적으로 해결이 가능할지 모르겠지만 요 부분은 살펴보겠습니다. 감사합니다.

**Comment by yelled1** [comment]
$ export | grep dasom
declare -x GTK_IM_MODULE="dasom"
declare -x QT4_IM_MODULE="dasom"
declare -x QT_IM_MODULE="dasom"
declare -x XMODIFIERS="@im=dasom"
이렇게 나옵니다. .xinput.d는 ignore 되는 듯 합니다.
카카오는 2.0.8.99 version이전에서는 나비에서도 문제가 없었습니다. 갑자기 이틀전 부터 문제가 되더군요.
문제는 2.0.8.999 에서도 발생하고 
한컴이나 MS Office 2010 문제는 나비에서 발생안하는데 notepad 에서도 다솜에서 생기는 문제는 한컴과 MS Office가 유사합니다. 
우선 notepad를 겨냥해서 문제를 debug하시는 것이 좋을 듯 합니다. 물론 카카오도 문제지만 다른 wine program에서 발생하는 문제와는 넘 차이가 큽니다.
한글이 리눅스에서 제데로 입력되지 않는 문제는 참 안타까운 일 입니다. XP와 active-x 덕분에 바이러스 지옥과 IT 후진국이 되고 있는데... 
의미있는 일을 하시는데 bug reporting 이왜 도와 드릴 수가 없내요.
혹시 영어로된 website 같은 것이 이해가 잘 안되시는 부분이 있다면 제가 번역/이해는 도움될지 모르겠습니다. 영어가 1st language 라서요.

**Comment by cogniti** [comment]
입력기 원리가 단순하여 소스코드가 몇 줄 되지 않습니다.
코딩에 소요되는 시간보다 테스트에 소요되는 시간이 2~4배 들어갑니다. 그래서 버그 리포팅이 개발에 중요한 부분을 차지하고 있습니다.
말씀하신 부분은, 나비와 다솜으로 노트패드를 시험해보겠습니다.
감사합니다.

**Comment by cogniti** [comment]
부득이한 사정으로 다솜 입력기에서 한국어 엔진을 제거하기로 하였습니다. 따라서 이 이슈를 닫겠습니다.
죄송합니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#24
