### ISSUE TITLE
설정기(dasom-settings)를 만들어 주시면 좋겠습니다.

### ISSUE THREAD

**Issue by bagjunggyu** [cogniti/dasom#27]
* 한/영키를 원하는 키(한/영)나, 키 조합(Shift+Space)등 으로 지정하고
* 오른쪽 alt를 한자나 한/영 키로 지정하고 싶을때
* compose 키를 지정하고 그 키를 한자나 한/영 키로지정하고 싶을때
등 , 이런 설정을 쉽게 할 수 있도록 해주는 도구를 만들어 주시면 좋겠습니다.

**Comment by sukso96100** [comment]
안녕하세요. 프로젝트가 github.com/dasom-im 으로 이전되었으므로. 여기 말고 github.com/dasom-im/dasom 에 이슈를 옮겨주시면 감사하겠습니다. 한글 입력 관련 이슈는 github.com/dasom-im/dasom-jeongeum 에 남겨주세요.
