### ISSUE TITLE
Zorin os 10 용으로.. 패키징을 해주실 수 있을까요?

### ISSUE THREAD

**Issue by JonghwaYoo** [cogniti/dasom#28]
우분투 15.04 기반의 배포판입니다.

qtbase-abi 관련으로 1.1 의 15.10 을 대상으로 하는 버전이 설치가 안되더군요..
(정확히는 qt 관련된 부분만 설치가 안되는것 같습니다만...)

혹시 zorin os 10 또는 우분투 15.04 기반으로 compile 된 deb 패키지를 요청드려도 될까요?

**Comment by cogniti** [comment]
https://github.com/dasom-im/dasom/issues/35
