### ISSUE TITLE
크롬을쓸때 버그가 생겼네요

### ISSUE THREAD

**Issue by jgyuseok** [cogniti/dasom#29]
크롬버전은 45.0.2454.101 Ubuntu 14.04 (64-bit) 사용중이고 우분투 14.04 LTS 에 KDE데스크탑 환경 깔아 서 쓰고있습니다 

다른 프로그램은 문제가 없는데 크롬만 이렇 게띄어쓰기 가이상하게 되네 요

다솜 입력기만 그런것이 아니라 ibus도 같은 현상이 있네요 잘쓰다 어느순간 갑자기 이렇게된거라 정확히 언제 오류가 났는지는 파악이 안됩니다

**Comment by cogniti** [comment]
제 생각엔 dasom-gtk 가 설치되지 않은 것 같습니다. 사용 중인 dasom 버전과 배포판 종류와 배포판 버전을 알려주세요.
2015. 12. 8. 오후 12:51에 "jgyuseok" <notifications@github.com>님이 작성:

**Comment by jgyuseok** [comment]
kubuntu 14.04에 다솜은 1.0버전 사용중입니다

**Comment by cogniti** [comment]
다음의 명령으로 공식 다솜 PPA 저장소 추가합니다.

sudo add-apt-repository ppa:dasom/ppa

공식 다솜 PPA 저장소 추가 후에

sudo apt-get update
sudo apt-get install dasom dasom-gtk dasom-qt dasom-jeongeum

로그아웃, 로그인하시고
크롬을 실행해 보시고 결과 알려주세요.
2015. 12. 8. 오후 2:20에 "jgyuseok" <notifications@github.com>님이 작성:

**Comment by jgyuseok** [comment]
여전히 같은증상이 일어납니다

**Comment by cogniti** [comment]
터미널에서
export | grep ibus
실행하여 결과를 올려주세요.

export | grep dasom
실행하여 결과를 올려주세요.
2015. 12. 8. 오후 2:41에 "jgyuseok" <notifications@github.com>님이 작성:

**Comment by jgyuseok** [comment]
export | grep dasom은 XMODIFIERS='@im=dasom'
export | grep ibus 은 아에 안나옵니다

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom-gtk#2
