### ISSUE TITLE
리베로 오피스에서 같은 라인글이 글쓸때 떨려요.

### ISSUE THREAD

**Issue by iyagicom** [cogniti/dasom#4]
리베로 오피스 쓰면서 정말로 말도 못하게 짜증낫는데 속시원하네요.
좋은 일 하셨어요~

리베로 오피스 측에서 잡아야 되는건지 모르겠지만요
쓰는데는 괜찮지만 언젠가는 잡혀야 될것 같아요.

**Comment by cogniti** [comment]
라인글이 글 쓸때 떨린다는 의미가... 글자를 입력할 때 한줄이 깜박거린다는 의미인가요?

**Comment by iyagicom** [comment]
좌우로 스텝을 밟듯이 춤을 쳐요
리브로는 아주 가끔씩쓰고 이번에 간만에쓴거라서요
올래 리브로 버그인지도 모르겠어요.
중앙정열 테이블에서 그래요.
첨부화일 확장자가 ogv인데 gif로 바꾸었어요.
![out-1](https://cloud.githubusercontent.com/assets/15052400/10408736/4f85304a-6f41-11e5-9dcd-da4d271ebf37.gif)

**Comment by cogniti** [comment]
그 현상은 preedit start, end, changed signal 문제 때문에 발생할 수도 있어서 확인을 해볼 필요가 있으니
사용하시는 배포판 종류와 버전, 리브레 오피스 버전을 말씀해주세요.

**Comment by iyagicom** [comment]
리눅스 민트 17 입니다. 
17.1과 17.2까지 나온걸로 알고 있어요.

리브레 버전: 4.2.8.2
빌드 번호: 420m0(Build:2) 입니다.

# uname -a
Linux iyagi 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/linuxmint/info 
RELEASE=17
CODENAME=qiana
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17 Qiana"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_qiana_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_qiana_cinnamon.php
USER_GUIDE_URL=http://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 17 Cinnamon 64-bit

**Comment by cogniti** [comment]
확인해보았는데 리브레 오피스 버그도 아니고 입력기 버그도 아닙니다.

그런 증상이 나타나는 이유는

1. 리브레 오피스 갱신이 느린 문제
2. 통신 구조의 입력기에서 나타나는 지연
3. 한글 엔진에서 commit 하기 전에 preedit text 를 지우고 commit

하기 때문입니다.

정음 엔진의 아래 코드가 영향을 주는 부분입니다.

https://github.com/cogniti/dasom/blob/0338a31a4e64b25184075e993288580ee7a8610b/modules/engines/dasom-jeongeum/dasom-jeongeum.c#L330

원래 조합 논리는...
`ㅎㅏㄴㄱㅡㄹ` 이라고 입력할 때,
`ㅎ` 을 누르면 `preedit-start`, `preedit-changed` 신호 발생,
`ㅏㄴ`을 누르면 `preedit-changed`  신호 발생,
`한`이 조합 중일 때 `ㄱ`을 누르면 `preedit-end`, `preedit-start`, `preedit-changed` 신호 발생...
이렇게 하였었는데.. XIM을 고려하면서 지금의 형태로 단순하게 변경하게 된 것 같습니다.
지금의 조합 논리는 imhangul, ibus-hangul 의 조합 논리와 같을 겁니다.
그래서 통신 구조의 ibus-hangul 에서도 마찬가지 현상이 나타납니다.
조합 신호(`preedit-start`, `preedit-changed`, `preedit-end`)를 보내는 더 나은 방법에 대해 앞으로 고려해볼 필요가 있습니다.

**Comment by cogniti** [comment]
현재의 방법은 preedit 를 지우고 업데이트하고 commit 하고 preedit 를 업데이트하는 과정을 거치고 있습니다. 이것을 단순화하여 commit 하고 preedit 를 업데이트하도록 해보니 XIM 에서 띄어쓰기 문제와 facebook 검색어 입력 문제까지 해결되는 것같습니다. 그런데 이 방법은 여러 어플에서 문제가 있는지 없는지 테스트를 해봐야됩니다.

그리고, `preedit-changed` 다음에는 항상 `get_preedit_string()` 함수가 호출되어 클라이언트, 서버간에 통신이 2번 이루어집니다. `preedit-changed(with text)` 에 text 를 실어서 통신을 1번으로 줄여보니 부하가 많이 감소하는 것 같습니다.

이렇게 두가지 방법을 적용하여 버추얼박스에서 리브레 오피스로 테스트해보니, 좌우로 출렁이는 현상이 사라졌습니다. 좀더 테스트 후에 커밋 올라갈 예정입니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#4
