### ISSUE TITLE
노트북에서 한자키 동작 안함

### ISSUE THREAD

**Issue by parkmino** [cogniti/dasom#5]
이번에 정식 버전이 나와서 예전에 컴파일했던 버전을 다 지우고 새로 설치했습니다.
이후로 노트북에서 한자키가 작동을 안 하네요.
제가 다른 걸 잘 못 건들였는지는 모르겠지만요.
한글도 'alt-r'을 추가해야 제대로 인식을 하는데, 이건 예전에도 마찬가지였지만 한자 입력은 'hangul-hanja'로 잘 되었거든요.
시간 나실 때 한번 봐 주시면 감사하겠습니다.
우분투 15.04 32비트입니다.

**Comment by cogniti** [comment]
일단... 전에 것(8월경쯤)과 조금 바뀐 것이 있습니다.
바뀐 점이...

1. 노트북 자판(또는 영문 자판) 설정법
2. 라이브러리 버전 삭제함.

그래서...

`find /usr/local | grep dasom`
`find /usr/local | grep Dasom`

명령 내려서 수작업으로 깨끗하게 모두 삭제해주시고...
(특히 `libdasom.so.0.0.0` `libdasom.so.0.0` `libdasom.so.0` 필히 삭제해햐 함.)

`dasom_1.0-<맞는 배포판>.deb` 를 설치해주세요...
그 후에...
`dconf-editor` 를 실행하여...
아래글 보시고 설정하시면 되겠습니다.
https://forum.ubuntu-kr.org/viewtopic.php?f=2&t=28262&start=10#p125472

예전에 키 설정에... `alt-r`, `ctrl-r` 이런거 넣었던 것 같은데...
지금 1.0 버전은...
`hangul-keys` 에... `hangul`,
`hanja-keys` 에 `hangul-hanja` 이렇게 기본값으로 변경해주세요.

`korean-101-104-key-compatible [v]` 체크
잘 될 겁니다.

**Comment by parkmino** [comment]
말씀하신대로 dconf-editor 설정을 하니 해결되었습니다.
감사합니다!

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#5
