### ISSUE TITLE
Dasom Agent 관련 문의 및 요청

### ISSUE THREAD

**Issue by sukso96100** [cogniti/dasom#7]
뒤늦게 말하는 거지만... 일단 이런 좋은 입력기 개발해 주셔서 감사합니다.
그놈 확장이능인 Dasom Agent에 대해 여쭤볼 것이랑, 추가되었으면 하는 기능이 있습니다.

1.아치리눅스의 경우, 아래 링크에서처럼 libc.conf 파일을 따로 만들어야 작업해야 Dasom Agent 가 작동이 되는데. 이게 다솜 자체의 문제인지, 아치리눅스의 문제인이 알고 싶습니다. 다솜 쪽 문제가 아니라면, 패키지의 설치 스크립트에 libc.conf 를 수정하는 코드를 넣을까 생각해 보고 있습니다.

2.이전에 Fcitx 랑 Input Method Panel 이란 그놈 확장기능(https://extensions.gnome.org/extension/261/kimpanel/) 같이 사용하면, Input Method Panel 켜면, Fcitx 의 표시기는 숨겨 지더군요. 다솜도 Dasom Agent 켜질 때, Dasom Indicator 가 숨겨지고, Dasom Agent 만 보이도록 하면 좋을 것 같습니다.

**Comment by cogniti** [comment]
1. 아치 리눅스의 문제도 아니고 다솜 입력기의 문제도 아닙니다. 아마도 `/usr/local` 에 라이브러리가 설치되었을 것 같은데... `/etc/ld.so.conf` 또는 `/etc/ld.so.conf.d/` 에 `/usr/local/lib` 경로가 없어서 발생하는 문제일텐데... `/usr/lib`, `/lib`는 필수적으로 경로가 들어있을 것이니... `/usr/lib`에 설치하시면 되겠습니다.
`./autogen.sh --prefix=/usr` 또는 `./configure --prefix=/usr` 하면 `/usr` 디렉토리에 설치될 것입니다.
*(`--prefix=/usr` 를 지정하지 않는 경우, 기본값은 `/usr/local`에 설치가 됩니다. `/usr/local`을 기본값으로 두는 이유는 외부에서 받은 프로그램 설치 경로와 각각의 배포판에서 제공하는 패키지 설치 경로가 겹치지 말라고 전통적으로 그렇게 하고 있습니다.)*

2. 그 부분은 고려를 해봐야 됩니다. 제가 사실... gnome shell extension 을 개발하고 싶지가 않습니다. JS 에 익숙치 않고 문서화가 잘 되어 있지 않아서 역설적으로 C 로 개발하는 것보다 10배 정도의 시간이 더 소모됩니다. GTK 와 appindicator 라이브러리라면 1시간이면 만들 수 있는 것을 JS를 사용하면 10시간이 걸리고 GNOME shell 버전이 올라갈 때마다... 좀 겁이 납니다. 신버전에 맞추어 코드를 수정하면 하위 호환성이 깨질텐데요... C에서는 조건부 컴파일이라도 하지만,, JS는 어떻게 해야하는지 전혀 모릅니다. 요청하시는 기능은 매우 간단한 것 같은데... 그걸 알려면 소스코드를 헤집고 뒤져봐야 하는데...한 이틀... 걸립니다. 그래서 gnome shell JS 쪽은 아예 개발하고 싶지가 않습니다.
`dasom-indicator` 에서는 en / ko 아이콘이 변화되는데...
dasom agent for gnome shell(이하 dasom-agent 라 부르겠습니다.) 에서는 글자로 표현하고 있죠... dasom-indicator 에 나오는 것과 비슷하게 만들려고 해도 할 줄 몰라서 못하고 있는 것입니다.
dasom-agent 에 보면 About (정보) 메뉴가 있는데.. 그거 만드는데 이틀 걸렸습니다. 마땅히 문서가 없어서 `gnome-shell-3.14.4/js/ui/*.js` 소스코드 분석해서 만들은 겁니다. 그 정도로 어렵습니다.
게다가 에러나면 그냥 안 된다고 메시지만 나오지... 자세히 나오질 않아서 디버깅이 C로 개발하는 것보다도 매우 까다롭습니다.
그래서 `appindicator` 라이브러리를 사용한 `dasom-indicator` 만 개발하는 것에 대해 고려 중입니다.
dasom-agent for gnome shell 이 없어도 `dasom-indicator` 로 gnome shell panel 에 표시할 수 있습니다. 우분투 패널에 나오는 것이라 똑같이 나옵니다. 개발은 이게 휠씬 쉽고 편합니다.

https://extensions.gnome.org/extension/615/appindicator-support/ 를 설치하시면 신비롭게도 `dasom-indicator` 가 GNOME shell panel 속으로 쏙 들어갑니다. 그 원리는 모르겠습니다만, GNOME shell panel, GNOME panel, Unity, KDE 현존하는 거의 모든 환경에서 동일한 표시기를 제공할 수 있습니다.
그래서 좀 고려 중에 있습니다.

**Comment by sukso96100** [comment]
답변 감사합니다. 그렇다면, 패키지 빌드 스크립트 에는 `./autogen.sh --prefix=/usr`랑 `./autogen.sh` 중 어느것을 넣는것이 더 좋을까요? `dasom-indicator` 만 개발하시는 것을 고려 한다면, `./autogen.sh` 로 해 두는것이 좋을까요?

**Comment by cogniti** [comment]
패키지 빌드 스크립트에는 `./autogen.sh --prefix=/usr` 이렇게 하시는 것이 좋을 것 같습니다.
그렇게 하면 `libdasom.so` 가 `/usr/lib` 또는 `/usr/lib/아키텍쳐/` 디렉토리에 위치하게 됩니다.
참고로, https://extensions.gnome.org/extension/615/appindicator-support/ 이 물건을 사용해보시고 의견을 좀 주시면 고맙겠습니다.

**Comment by cogniti** [comment]
개발 초기에 (appindicator 을 알았더라면 좋았을껄...) 우분투에서도 GNOME shell 이 돌아가는 줄 알았습니다. ㅎㅎㅎ
![dasom-indicator-in-gnome-shell-panel](https://cloud.githubusercontent.com/assets/9195462/10417324/7bb538b8-7072-11e5-889e-cc1ff56e088b.jpg)
스크린샷입니다. en1 왼쪽의 회색 네모 박스가.. `dasom-indicator` 입니다.. 이렇게 들어갑니다.

**Comment by sukso96100** [comment]
감사합니다 `./autogen.sh --prefix=/usr` 로 수정했습니다. 알려주신 확장기능 써 보는 중 인데, `dasom-indicator`가 패널에 깔끔하게 들어가서 정말 좋네요 ㅎㅎ
![2015-10-11 23-45-54](https://cloud.githubusercontent.com/assets/1916739/10417341/367e8c58-7073-11e5-94a3-7a4c23bda08b.png)

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#7
