### ISSUE TITLE
XIM: chromium에서 한글 띄어쓰기 문제가 발생합니다.

### ISSUE THREAD

**Issue by lockpick** [cogniti/dasom#8]
arch linux를 사용하고 있습니다.
KDE 프레임워크 5.14.0 (Qt 5.5.0으로 빌드됨)
chromium : 버전 46.0.2490.71 (64-bit)

글자 를입력 한후 에띄어쓰기 를하 면이렇 게됩니다.
글자 를입력하 는도중 에커서 를이동하 면커서 의최종위치 에글자 가이동합니다.

"안녕하세요" 를입력 한 후왼 쪽화살표 를입력하 면다음  과같 이됩니다.
안녕하요세

**Comment by lockpick** [comment]
추가로, Qt 어플리케이션에서 는한  영전환 이안됩니다.

[han@han ~]$ env | grep IM_MODULE
QT_IM_MODULE=dasom
GTK_IM_MODULE=dasom

[han@han ~]$ env |grep XMODI
XMODIFIERS=@im=dasom

**Comment by cogniti** [comment]
현재 svg --> png 아이콘 변환을 자동화하는 Makefile.am 커밋을 준비 중이므로 그 이후 살펴보겠습니다.

**Comment by cogniti** [comment]
아치리눅스에서 chromium : 버전 46.0.2490.71 (64-bit) 으로 테스트해봤습니다.
gtk im 모듈(`dasom_gtk_im_context_new`)이 구동되며 이상이 없습니다.
테스트는 이렇게 할 수 있습니다.
터미널을 열고
`export | grep dasom` 하여 환경 변수가 적절한지 확인하고..
`export G_MESSAGES_DEBUG=dasom` 해주고,
`chromium`
이렇게 실행하면 디버깅 메시지가 출력됩니다.
메시지가 너무 많이 출력되므로...
`chromium | grep dasom_gtk_im_context_filter_keypress`
이렇게 하여 타이핑할 때 메시지가 올라가는 것이 확인되면 gtk im 모듈이 사용되는 것입니다.

그리고 Qt 어플인 kate 에서 qt5 im 모듈이 로딩되지 않는 것을 확인하여 원인 파악 중입니다.

**Comment by cogniti** [comment]
크로미엄 사용할 때 다솜 입력기의 gtk im 모듈이 작동하는지 확인 부탁드립니다. 확인 방법은 위에 있습니다.

**Comment by cogniti** [comment]
lockpick 님 크로미엄 사용할 때 gtk im 모듈이 작동하지 않는다면 다솜 입력기가 제대로 설치되지 않았거나 어딘가에 설정에 문제가 있을 것으로 짐작됩니다.
크로미엄에서
` 글자 를입력하 는도중 에커서 를이동하 면커서 의최종위치 에글자 가이동합니다.`
이렇게 글자가 나오는 경우가 있긴 있는데,
그러한 현상은
`GTK_IM_MODULE="xim"`
이렇게 설정하면 재현할 수 있습니다.
XIM 으로 입력할 때 그러한 현상이 나타납니다.
다솜 입력기의 XIM 처리는 `IMdkit` 라는 라이브러리로 처리하므로
IMdkit 를 사용하고 있는 ibus, nabi, dasom 등에서 두루 나타나는 현상입니다.
따라서 gtk im 모듈이 정상적으로 작동할 수 있도록 다솜 입력기를 재설치하시거나 입력기 설정을 확인하시기 바랍니다.
XIM 이슈가 해결되기를 바라시면 따로 XIM 이슈를 만드시기 바랍니다. 다른 이슈 및 개발 계획에 밀려서 IMdkit 을 제거하고 XIM 부분을 새로 작성하려면 몇 년 후에나 시작할 수 있을 것 같고, 개발 기간은 6개월 가량 걸릴 것 같습니다.
그리고 Qt 5.5 에서 호환성 문제는 (아직 확인해보지 않았지만) 다른 이슈에서 제기된 것 같고, 제가 인지하고 있는 부분이므로 이 이슈를 닫겠습니다.
감사합니다.

**Comment by cogniti** [comment]
애초에 IMdkit 의 문제로 추정했으나, XIM 을 사용하는 Android Studio 1.4 와 Libreoffice 는 띄어쓰기가 오류가 발생하지 않는 것으로 보아 IMdkit 의 문제가 아닌 것 같습니다. 이 문제는 크로미엄의 XIM 처리부의 문제로 추정됩니다.
https://code.google.com/p/chromium/issues/detail?id=354495

**Comment by lockpick** [comment]
![test](https://cloud.githubusercontent.com/assets/13410916/10597786/5a94206a-772d-11e5-9dc1-4481ce3c9bec.png)

방 금재설 치하 고재부 팅한 후테스트 한스크린 샷입니다.
지금 도분명 히QT_IM_MODULE="dasom" 입니다.

**Comment by lockpick** [comment]
![test1](https://cloud.githubusercontent.com/assets/13410916/10597942/0fdb0fe6-772f-11e5-8421-8668e8b28157.png)
![test2](https://cloud.githubusercontent.com/assets/13410916/10597943/10fb0cbe-772f-11e5-901d-8e461461fb82.png)

지금 도 분명히GTK_IM_MODULE="dasom" 입니다.
이렇 게입력되 고있습니다.

**Comment by cogniti** [comment]
터미널을 열고
export | grep dasom 하여 환경 변수가 적절한지 확인하고..
export G_MESSAGES_DEBUG=dasom 해주고,
chromium
이렇게 실행하면 디버깅 메시지가 출력됩니다.
메시지가 너무 많이 출력되므로...
chromium | grep dasom_gtk_im_context_filter_keypress
이렇게 하여 타이핑할 때 메시지가 올라가는 것이 확인되면 gtk im 모듈이 사용되는 것입니다.
타이핑할 때 dasom_gtk_im_context_filter_keypress 이 메시지가 나와야 합니다. 이 메시가 나오는지 알려주세요

**Comment by cogniti** [comment]
생각해보니 Qt 환경에서 크로미엄을 돌려본적이 없는데 확인해보겠습니다. 감사합니다.

**Comment by cogniti** [comment]
데비안 jessie 에서 kdm 으로 로그인하고, 플라즈마 데스크탑이고,
Version 45.0.2454.85 Built on 8.1, running on Debian 8.2 (64-bit)
에서 다솜 입력기가 잘 작동합니다.

아치리눅스에서 gdm3 으로 로그인하고, GNOME 환경에서 konsole 에서 chromium 실행했을 때 다솜 입력기가 잘 작동합니다.

아치리눅스에 KDE 환경을 설치하긴 했는데, 어떻게 KDE 관련 Display Manager로 로그인을 해야 하는지 모르겠네요. 그 방법을 좀 알려주세요.

**Comment by cogniti** [comment]
아치리눅스를 `pacman -Su` 하였습니다. 문서는 https://wiki.archlinux.org/index.php/Pacman_%28%ED%95%9C%EA%B5%AD%EC%96%B4%29 를 참고했습니다.
그리고,
아치리눅스에 입력기가 다솜 하나밖에 안 깔려있습니다. 다른 입력기들은 아치에서 어떻게 설정해야 하는지 잘 몰라서요.
그리고... 전에 gdm3 으로 로그인했었는데...
이번에.. `pacman -S kdebase-workspace` 를 설치했습니다. 거기에 kdm 도 들어있는지는 모르겠고,
`systemctl disable gdm.service`
`systemctl enable kdm.service`
한 후 리부팅하여 kdm 으로 로그인 후,
해봤는데... 다 잘됩니다.

**Comment by cogniti** [comment]
다솜 입력기 문제는 확실히 아닙니다.
아마 시스템 설정이나 어딘가에 문제가 있을 것으로 보입니다.
제가 아치 리눅스를 모르기 때문에 해결해 드릴 수 있는 부분이 없습니다.
아치 리눅스 커뮤니티에 문의하시기 바랍니다.
감사합니다.

인증샷입니다.
![screenshot from 2015-10-20 17 48 31](https://cloud.githubusercontent.com/assets/9195462/10602372/dca0f1d0-7752-11e5-9711-dc3cf93ba348.png)

아래 보시면 키 입력할 때 dasom gtk im 모듈이 정상적으로 로딩되었음을 확인할 수 있습니다.
![screenshot from 2015-10-20 17 48 56](https://cloud.githubusercontent.com/assets/9195462/10602373/dca55202-7752-11e5-95b3-ea5438863e97.png)

**Comment by cogniti** [comment]
혹시나 해서 dasom 모두 삭제하고 `find /usr | grep dasom` 으로 모두 삭제된 것 확인하고,
`git clone https://github.com/cogniti/dasom` 하여 소스 컴파일하여 다시 설치해봤는데 잘 됩니다.
AUR 설치는 몇번씩 시도했으나 에러나서 포기했습니다.
그래서 AUR 통하여 설치할 경우, 정상 작동하는지 그건 테스트해보지 못했습니다.

**Comment by lockpick** [comment]
kdm 은 kde plasma 5에 불가능하다고 하여 sddm 을 사용중입니다.
다음은 archlinux wiki의 내용 중 일부입니다.

KDM is not available in Plasma 5. KDE upstream recommends using the SDDM display manager as it provides integration with the Plasma 5 theme.

혹시, 시스템상의 다른 문제일 수도 있으므로, 재설치해보겠습니다.
그리고 설치 과정의 명령어도 적어서 올리겠습니다.

**Comment by cogniti** [comment]
아직 재설치하지 마시고요... 혹시 Qt는 되나요? 그리고 gtk im 캐시 업데이트 하셨는지요... git 로 최신 커밋 받아서
README 파일에 나오는데로 해보세요... ldconfig 도 빼먹으면 안되고 Troubleshooting 부분도 확인해보세요.
그리고 gtk im module 디렉토리 위치 확인하세요.
2015. 10. 21. 13:07에 "lockpick" <notifications@github.com>님이 작성:

**Comment by lockpick** [comment]
해보겠습니다.

**Comment by lockpick** [comment]
해보겠습니다. 
그리고 제가 스크린샷을 올린것 중 가장 위의 것이 Qt 의경우고요,  잘됩니다.

**Comment by lockpick** [comment]
AUR 패키지에 
sudo make update-gtk-im-cache
sudo make update-gtk-icon-cache
을 해주는 부분이 없네요.

이것을 dasom-git.install 의 post_install() 내에서 ldconfig 다음에 해줘야 할 것 같습니다.
그런데, post_install 단계에서는 Makefile이 존재하지 않으므로 make를 할 수 없습니다.

따라서, make install을 할 때, cache관련 작업을 해주는 스크립트를 생성하고, post_install시점에서 이 스크립트를 실행하는 것이 적절할 것으로 보입니다.

p.s. dasom-git.install에서 sudo를 사용하신 것 같은데, root권한으로 실행되므로 sudo는 필요하지 않을 겁니다.

**Comment by lockpick** [comment]
git으로 수동 설치하니 잘 되었습니다. 그리고 문제점도 찾았습니다.

AUR 패키지에 
sudo make update-gtk-im-cache
sudo make update-gtk-icon-cache
을 해주는 부분이 없네요.

이것을 dasom-git.install 의 post_install() 내에서 ldconfig 다음에 해줘야 할 것 같습니다.
그런데, post_install 단계에서는 Makefile이 존재하지 않으므로 make를 할 수 없습니다.

따라서, make install을 할 때, cache관련 작업을 해주는 스크립트를 생성하고, post_install시점에서 이 스크립트를 실행하는 것이 적절할 것으로 보입니다.

p.s. dasom-git.install에서 sudo를 사용하신 부분이 보였는데, root권한으로 실행되므로 sudo는 필요하지 않을 겁니다.
p.s. AUR을 통한 설치는 일반적으로 yaourt패키지를 AUR에서 수동 설치한 후, yaourt -S dasom-git 을 통해서 설치하게 됩니다.

**Comment by sukso96100** [comment]
안녕하세요. 중간에 끼어들어서 죄송합니다만... AUR 에 있는 dasom-git 패키지는 현제 제가 관리하는 중입니다. 패키지에 문제 있으면 저에게도 예기해주세요. :)

**Comment by cogniti** [comment]
lockpick님 AUR 패키지는 제 관할 밖입니다.
https://aur.archlinux.org/cgit/aur.git/log/?h=dasom-git 보니 sukso96100 님께서 업데이트를 하신 것 같네요.
제가 AUR 을 몰라서 뭐라 드릴 말씀이 없네요.
10월 15일 커밋 https://github.com/cogniti/dasom/commit/37a4d97e0664b7c1813644dda880d1709f559f6b 에서 png 아이콘 생성을 자동화하면서 librsvg 이게 필요합니다. 데비안 패키지 이름(librsvg2-bin). 그리고 아마... 아이콘 글자가 이상하게 나오실 것 같은데... svg 파일에서 https://aur.archlinux.org/packages/ttf-noto-cjk/ 를 참조합니다. 컴파일하여 설치하시는 거라면 https://aur.archlinux.org/packages/ttf-noto-cjk/ 도 설치하시는 것이 좋습니다.

**Comment by lockpick** [comment]
문제점이 완벽히 해결되었습니다.
감사합니다.

**Comment by cogniti** [comment]
XIM 에서 띄어쓰기 문제가 발생하는 부부은 아무래도 입력기 버그 같기도 합니다.
오늘 테스트를 좀 해보았는데, commit 한 후에 preedit changed 또는 end 신호를 보내니 띄어쓰기 문제가 사라지는 것 같습니다. 아울러 페이스북에서의 문제도 사라지는 것 같습니다.

**Comment by cogniti** [comment]
commit before update preedit 하도록 소스를 수정한 후에,

1. chromium XIM 테스트를 해보니 입력하는 속도에 따라 띄어쓰기 문제가 발생하는 경우가 있고 아닌 경우가 있습니다. 그리고 commit 후에 조합 중인 자소가 화면에 표시가 안 되는 문제가 있습니다.

2. libreoffice XIM 의 경우, 끝글자가 마우스 클릭할 때 따라다는 것외에는 문제가 없는 듯하고,

3. gtk 어플 gedit, iceweasel 의 경우 xim 접속시 문제가 없는 것 같습니다.

별 의미 없습니다만, chromium XIM 입력이 약간 개선되었습니다.
 chromium XIM 버그는 입력기에서 해결이 안 되는 것 같습니다.

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#8
