### ISSUE TITLE
eclipse에서 마우스 우클릭이 되지 않습니다.

### ISSUE THREAD

**Issue by conr2d** [cogniti/dasom#9]
Elementary OS 0.3 Freya버전에서 Tizen SDK 2.4 beta에 포함된 eclipse 사용시 프로젝트 목록창에서 마우스 우클릭이 작동하지 않습니다.

**Comment by cogniti** [comment]
터미널 열고 아래 명령을 해보세요.
아래 명령은 마우스 클릭할 때 reset 에 관련된 설정입니다.
`gsettings set org.freedesktop.Dasom.clients.gtk reset-on-gdk-button-press-event false`

**Comment by cogniti** [comment]
어떤 걸 설치해야 하나요?
https://developer.tizen.org/development/preview?langredirect=1
버추얼박스로 테스트해보려고 하는데...
Elementary OS 0.3.1 Freya 설치 후에, 이클립스 설치하고, 타이젠 설치하면 되는 건가요?
아니면, 타이젠에 이클립스가 포함된 버전이 따로 있는 건가요?

**Comment by netman2k** [comment]
Ubuntu gnome 15.04에 Gnome 3.16를 올릴 경우도 안되네요.

**Comment by cogniti** [comment]
다솜 입력기의 이벤트 후킹 기능 때문에 그러한 현상이 발생될 가능성이 있습니다.

**Comment by cogniti** [comment]
터미널을 열어서 아래 명령을 입력한 후, 데스트탑 로그아웃, 로그인을 하면 이벤트 후킹 기능이 모두 꺼집니다. 다솜 입력기의 이벤트 후킹 기능을 모두 끈 상태에서도 마우스 클릭에 문제가 발생하는지 알려주세요.
```
gsettings set org.freedesktop.Dasom.clients.gtk hook-gdk-event-key false
gsettings set org.freedesktop.Dasom.clients.gtk reset-on-gdk-button-press-event false
```

**Comment by cogniti** [comment]
구글에서 검색해보니 eclipse 마우스 문제가 검색이 되는데...
입력기 문제가 아닌 것 같습니다.
http://stackoverflow.com/questions/25300416/right-click-in-eclipse-is-not-working
eclipse 프로젝트에 문의하시기 바랍니다.

**Comment by cogniti** [comment]
마우스 오른쪽 클릭시에 메뉴가 나와야 되는거군요...
버그 재현을 했고, 다솜 입력기의 버그가 맞습니다.

**Comment by netman2k** [comment]
이클립스 문제는 아닌 걸로 제가 확인을 했습니다.
시스템을 모두 재설치한 후 스냅샷을 떠가며 확인을 했는데요 (혹시나 업데이트로인한 라이브러리 문제가 있을지 몰라서...) 업데이트 후에
항상 이클립스를 띄운 후 컨텍스트 메뉴를 활성화하였는데요 gnome shell 3.16 환경 상에서 다솜입력기를 띄우니 더이상 컨텍스트
메뉴가 나오지 않았습니다. 다시 기존 사용하던 uim을 설치하니 그때는 잘 나오더군요

더 테스트가 필요하겠지만 제가 보기에는 이클립스 문제는 아닌 듯합니다

2015년 10월 17일 (토) 오전 1:10, Hodong Kim <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
해당 버그는
https://github.com/cogniti/dasom/blob/d329047ddcc88e1099f42d852b87356114abd6f2/modules/clients/gtk/im-dasom.c#L156
https://github.com/cogniti/dasom/blob/d329047ddcc88e1099f42d852b87356114abd6f2/modules/clients/gtk/im-dasom.c#L185
https://github.com/cogniti/dasom/blob/d329047ddcc88e1099f42d852b87356114abd6f2/modules/clients/gtk/im-dasom.c#L199
이 부분과 관련이 있습니다.

많이 불편하실텐데, 터미널을 열어서 아래 명령을 입력한 후, 데스트탑 로그아웃, 로그인을 하면 이벤트 후킹 기능이 모두 꺼집니다.
```
gsettings set org.freedesktop.Dasom.clients.gtk hook-gdk-event-key false
gsettings set org.freedesktop.Dasom.clients.gtk reset-on-gdk-button-press-event false
```
늦어도 11월까지는 수정할 계획입니다.

**Comment by conr2d** [comment]
이메일 확인을  못해서 이슈만 등록해놓고 달아주신 코멘트를 모르고 있었네요. 번거로우실텐데 직접 테스트해주시고 감사합니다. 정말 좋은 입력기 잘 사용하고 있습니다. 말씀해주신 방법 테스트해보겠습니다. :D

**Comment by iyagicom** [comment]
저도 이클립스에서 마우스 우클릭이 안되었는데 다솜입력기 때문이였나보네요.
별별것 다 해보다가 안되어서 안드로이드 스트디오로 갈아 탓는데 안드로이드 스트디오가 훨씬 좋네요 ㅎㅎ

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#9
